"""Functional and micro-operation IR for the strict architecture C-model."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping, Sequence

from .errors import ConfigurationError


class Operand(str, Enum):
    INPUT = "input"
    WEIGHT = "weight"
    OUTPUT = "output"


class MicroOpKind(str, Enum):
    START = "start"
    SRAM_READ = "sram_read"
    SRAM_WRITE = "sram_write"
    VLINK_SEND = "vlink_send"
    BUFFER_READ = "buffer_read"
    BUFFER_WRITE = "buffer_write"
    NOC_SEND = "noc_send"
    ARRAY_STEP = "array_step"
    LOCAL_REDUCE = "local_reduce"
    GLOBAL_REDUCE = "global_reduce"
    BARRIER = "barrier"


@dataclass(frozen=True, slots=True)
class GemmOp:
    """Bit-accurate GEMM functional operation.

    Semantics are ``C[M, N] = A[M, K] @ B[K, N]``. The C-model currently
    models integer storage and accumulation widths but does not silently infer
    quantization or saturation rules.
    """

    op_id: str
    m: int
    n: int
    k: int
    input_bits: int = 8
    weight_bits: int = 8
    accumulator_bits: int = 32

    def __post_init__(self) -> None:
        if not self.op_id:
            raise ConfigurationError("GEMM op_id must be non-empty")
        for name, value in (("m", self.m), ("n", self.n), ("k", self.k)):
            if value <= 0:
                raise ConfigurationError(f"GEMM {name} must be positive, got {value}")
        for name, value in (
            ("input_bits", self.input_bits),
            ("weight_bits", self.weight_bits),
            ("accumulator_bits", self.accumulator_bits),
        ):
            if value <= 0 or value % 8 != 0:
                raise ConfigurationError(
                    f"{name} must be a positive byte-aligned width, got {value}"
                )

    @property
    def mac_count(self) -> int:
        return self.m * self.n * self.k


@dataclass(frozen=True, slots=True)
class MappingSpec:
    """Explicit architecture mapping; no automatic fallback is permitted."""

    tile_m: int
    tile_n: int
    tile_k: int
    partition_dim: str = "N"
    prefetch_distance_cycles: int = 0

    def __post_init__(self) -> None:
        for name, value in (
            ("tile_m", self.tile_m),
            ("tile_n", self.tile_n),
            ("tile_k", self.tile_k),
        ):
            if value <= 0:
                raise ConfigurationError(f"{name} must be positive, got {value}")
        if self.partition_dim not in {"N", "K"}:
            raise ConfigurationError(
                f"partition_dim must be 'N' or 'K', got {self.partition_dim!r}"
            )
        if self.prefetch_distance_cycles < 0:
            raise ConfigurationError("prefetch_distance_cycles cannot be negative")


@dataclass(frozen=True, slots=True)
class OperandDemand:
    """One coalesced SRAM demand generated by the systolic backend."""

    cycle: int
    operand: Operand
    address: int
    nbytes: int

    def __post_init__(self) -> None:
        if self.cycle < 0:
            raise ConfigurationError("demand cycle cannot be negative")
        if self.address < 0:
            raise ConfigurationError("demand address cannot be negative")
        if self.nbytes <= 0:
            raise ConfigurationError("demand size must be positive")


@dataclass(frozen=True, slots=True)
class SystolicInvocation:
    op_id: str
    m: int
    n: int
    k: int
    array_rows: int
    array_cols: int
    dataflow: str
    input_bits: int
    weight_bits: int
    accumulator_bits: int


@dataclass(frozen=True, slots=True)
class SystolicResult:
    backend_name: str
    backend_version: str
    config_digest: str
    total_cycles: int
    utilization: float
    demands: tuple[OperandDemand, ...]
    raw_metrics: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.total_cycles <= 0:
            raise ConfigurationError(
                f"systolic backend returned non-positive cycle count {self.total_cycles}"
            )
        if not 0.0 <= self.utilization <= 1.0:
            raise ConfigurationError(
                f"utilization must be in [0, 1], got {self.utilization}"
            )
        if not self.demands:
            raise ConfigurationError("strict systolic result requires SRAM demand traces")


@dataclass(frozen=True, slots=True)
class MicroOp:
    """One schedulable micro-operation.

    A micro-operation owns exactly one resource. Multi-stage transfers are
    represented explicitly as chains (bank -> vertical link -> buffer -> array)
    rather than as one event that unrealistically locks all resources together.
    """

    uid: int
    name: str
    kind: MicroOpKind
    resource_id: str | None
    duration_cycles: int
    deps: tuple[int, ...] = ()
    release_anchor: int | None = None
    release_offset_cycles: int = 0
    nbytes: int = 0
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.uid < 0:
            raise ConfigurationError("micro-op uid cannot be negative")
        if not self.name:
            raise ConfigurationError("micro-op name must be non-empty")
        if self.duration_cycles < 0:
            raise ConfigurationError("micro-op duration cannot be negative")
        if self.release_offset_cycles < 0:
            raise ConfigurationError("release offset cannot be negative")
        if self.nbytes < 0:
            raise ConfigurationError("micro-op nbytes cannot be negative")
        if self.resource_id is None and self.duration_cycles != 0:
            raise ConfigurationError(
                "resource-free micro-ops must have zero duration; use a resource for work"
            )


@dataclass(frozen=True, slots=True)
class MicroProgram:
    operations: tuple[MicroOp, ...]
    terminal_uids: tuple[int, ...]
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        ids = [op.uid for op in self.operations]
        if len(ids) != len(set(ids)):
            raise ConfigurationError("duplicate micro-op uid")
        known = set(ids)
        for op in self.operations:
            missing = set(op.deps) - known
            if missing:
                raise ConfigurationError(
                    f"micro-op {op.uid} has unknown dependencies {sorted(missing)}"
                )
            if op.release_anchor is not None and op.release_anchor not in known:
                raise ConfigurationError(
                    f"micro-op {op.uid} has unknown release anchor {op.release_anchor}"
                )
        if not self.terminal_uids:
            raise ConfigurationError("micro-program needs at least one terminal event")
        missing_terminal = set(self.terminal_uids) - known
        if missing_terminal:
            raise ConfigurationError(
                f"unknown terminal events {sorted(missing_terminal)}"
            )


class MicroProgramBuilder:
    """Deterministic helper for constructing a micro-operation DAG."""

    def __init__(self) -> None:
        self._ops: list[MicroOp] = []
        self._next_uid = 0

    @property
    def next_uid(self) -> int:
        return self._next_uid

    def add(
        self,
        *,
        name: str,
        kind: MicroOpKind,
        resource_id: str | None,
        duration_cycles: int,
        deps: Sequence[int] = (),
        release_anchor: int | None = None,
        release_offset_cycles: int = 0,
        nbytes: int = 0,
        metadata: Mapping[str, Any] | None = None,
    ) -> int:
        uid = self._next_uid
        self._next_uid += 1
        self._ops.append(
            MicroOp(
                uid=uid,
                name=name,
                kind=kind,
                resource_id=resource_id,
                duration_cycles=duration_cycles,
                deps=tuple(deps),
                release_anchor=release_anchor,
                release_offset_cycles=release_offset_cycles,
                nbytes=nbytes,
                metadata={} if metadata is None else dict(metadata),
            )
        )
        return uid

    def build(
        self,
        terminal_uids: Sequence[int],
        metadata: Mapping[str, Any] | None = None,
    ) -> MicroProgram:
        return MicroProgram(
            operations=tuple(self._ops),
            terminal_uids=tuple(terminal_uids),
            metadata={} if metadata is None else dict(metadata),
        )
